export const setLeveler = (value: number) => {
  if (value < 20) return 'A'
  if (value < 40) return 'B'
  if (value < 60) return 'C'
  if (value < 80) return 'D'
  if (value < 100) return 'E'
  if (value < 120) return 'F'
  if (value < 140) return 'G'
  if (value < 160) return 'H'
  if (value < 180) return 'I'
  if (value < 200) return 'J'
  if (value < 220) return 'K'
  if (value < 240) return 'L'
  if (value < 260) return 'N'
  if (value < 280) return 'M'
}

export const setReLeveler = (value: number) => {
  if (value < 20) return 'A'
  if (value < 40) return 'B'
  if (value < 60) return 'C'
  if (value < 80) return 'D'
  if (value < 100) return 'E'
  if (value < 120) return 'F'
  if (value < 140) return 'G'
  if (value < 160) return 'H'
  if (value < 180) return 'I'
  if (value < 200) return 'J'
  if (value < 220) return 'K'
  if (value < 240) return 'L'
  if (value < 260) return 'N'
  if (value < 280) return 'M'
}
